### ISSUE TITLE
 j.tools.tfgrid_simulator object raise error 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_libs_extra#20]
j.tools.tfgrid_simulator
```
Traceback (most recent call last):
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py", line 130, in _discover_group
    attr = getattr(group, factory)
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1074, in tfgrid_simulator
    from JumpscaleLibsExtra.tools.threefold_simulation.TFGridSimulatorFactory import TFGridSimulatorFactory
  File "/sandbox/lib/jumpscale/JumpscaleLibsExtra/tools/threefold_simulation/TFGridSimulatorFactory.py", line 3, in <module>
    from .TFGridSimulator import TFGridSimulator
  File "/sandbox/lib/jumpscale/JumpscaleLibsExtra/tools/threefold_simulation/TFGridSimulator.py", line 6, in <module>
    from .TokenCreator import TokenCreator
ImportError: cannot import name 'TokenCreator'
```

**Comment by waleedhammam** [comment]
can't reproduce anymore on current image

on fresh installation:
![Screenshot from 2020-05-26 14-37-57](https://user-images.githubusercontent.com/10658229/82901647-88422580-9f5e-11ea-8808-88f0dfb3b64a.png)
